Get category
Ryoma137/record-of-expense pull request #7
Opened 2022-05-31 02:50 UTC by Ryoma137

- testFindAllをtest-schema.sql内に作成
 - カテゴリー一覧をDBから取得
        	- repositoryでデータを絞るように作成
        		→ getCategoryListをAmountRepository内に作成
                         → getAmountByCategoryのメソッドをAmountService内に作成
        	- controller作成	
        - カテゴリー一覧をDBから取得テストケース作成
        		→ testGetCategoryをtest-schema.sql内に作成

2022-05-31 05:12 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/AmountService.java
>  public class AmountService {
好みの問題ですが、AmountService がおかれているパッケージがプロジェクト直下であることが気になります。
controller / entity / repository が一階層下のパッケージなら、service パッケージを作って格納した方が納まりがいい気がします。

2022-05-31 05:12 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/AmountService.java
> +    public List<String> getAmountByCategory() {
こちらのメソッドは、処理内容と名称が一致していますか？

2022-05-31 05:12 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/controller/IncomeController.java
>      private final AmountRepository amountRepository;
Controller で Service を使わずに Repository を直接使っているのは何故ですか？

2022-05-31 05:12 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/controller/IncomeController.java
> +        List<String> categoryList = StreamSupport.stream(amountRepository.getCategoryList().spliterator(),false).toList();
getCategoryList() の返値を、一度ストリームにしてリストにしているのは何故ですか？

2022-05-31 05:12 UTC, t-ita commented on src/test/java/com/recordofexpense/recordofexpense/AmountServiceTest.java
> +        assertEquals("Food", actual.get(0));
テストケースが不十分です。
 category 一覧を取得するにあたって、正しく取得出来ていることを担保できるテストデータとテストケースを考えてみましょう。（テストデータに付いては下記にヒントを記載しています）

2022-05-31 05:12 UTC, t-ita commented on src/test/resources/test-schema.sql
>  (2,'White T-Shirt',980,'Clothes','Uniqlo T-Shirt'),
テストデータが不十分です。
一つのカテゴリに対して複数レコードを用意するようにしてください。
お小遣い帳のデータとして、Food カテゴリのレコードが1件、なんてことないですよね？

2022-05-31 05:12 UTC, t-ita commented on src/test/java/com/recordofexpense/recordofexpense/repository/AmountRepositoryTest.java
> +class AmountRepositoryTest {
利用していないソースコードは、追加しないでおきましょう。レビューのノイズになります。

2022-05-31 13:34 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/AmountService.java
>  public class AmountService {
Reply のテスト

2022-06-01 01:13 UTC, t-ita reviewed
Review のリクエストが来ていたので、一度レビューした体をとる。

2022-06-01 01:43 UTC, Ryoma137 commented
test

2022-06-01 01:51 UTC, Ryoma137 reviewed
修正してコメントしました。

2022-06-01 01:51 UTC, Ryoma137 commented on src/main/java/com/recordofexpense/recordofexpense/AmountService.java
>  public class AmountService {
test

2022-06-01 01:51 UTC, Ryoma137 commented on src/test/java/com/recordofexpense/recordofexpense/repository/AmountRepositoryTest.java
> +class AmountRepositoryTest {
test

2022-06-01 01:51 UTC, Ryoma137 commented on src/main/java/com/recordofexpense/recordofexpense/AmountService.java
> +    public List<String> getAmountByCategory() {
> こちらのメソッドは、処理内容と名称が一致していますか？

test

2022-06-01 02:03 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/AmountService.java
>  public class AmountService {
OKです。

2022-06-01 02:09 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/AmountService.java
> +    public List<String> getAmountByCategory() {
確認しました。

2022-06-01 02:10 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/controller/IncomeController.java
>      private final AmountRepository amountRepository;
確認しました。

2022-06-01 02:13 UTC, t-ita commented on src/test/java/com/recordofexpense/recordofexpense/repository/AmountRepositoryTest.java
> +class AmountRepositoryTest {
確認しました。

2022-06-01 02:16 UTC, t-ita commented on src/test/java/com/recordofexpense/recordofexpense/AmountServiceTest.java
> +        assertEquals("Food", actual.get(0));
@Ryoma137 テストは、メソッドの仕様を確認するためのものですが、このメソッドの仕様はこの結果でよいのでしょうか？
石崎さんが考えるカテゴリ一覧取得機能の仕様は、Food が3件、Clothes が3件、Gadget が3件返ってくる仕様で問題無いですか？

2022-06-01 02:18 UTC, t-ita requested changes
いくつか会話を解決済みにしましたが、テストが正しいか不明なのでコメントを返しています。確認をお願いします。

2022-06-01 07:37 UTC, Ryoma137 commented on src/test/resources/test-schema.sql
>  (2,'White T-Shirt',980,'Clothes','Uniqlo T-Shirt'),
1件のレコードと複数のレコードが混在するようにテストデータとテストケースの修正

2022-06-02 04:46 UTC, Ryoma137 commented on src/test/java/com/recordofexpense/recordofexpense/AmountServiceTest.java
> +        assertEquals("Food", actual.get(0));
テストの仕様を以下のように変更しました。
　　 1. リスト(getCategoryList)の中にカテゴリー名の文字列が入っているかのテストに変更
　　 2. DBから取得したカテゴリー名を重複を省き取得
また、テストに記述された仕様に合わせて実装も同じカテゴリー名が重複されないように変更しました。

2022-06-02 06:11 UTC, t-ita approved these changes
テストを見る限り、処理の仕様は問題無さそうです。現時点では、OK です。

2022-06-03 03:00 UTC, Ryoma137 commented
DBから取得したカテゴリーをdrop downで表示するためのthyemleaf機能を追加したのでレビューお願いします。 @t-ita

2022-06-03 03:15 UTC, t-ita requested changes
細かい事ですが、変数の名付けについて指摘します。
変数名などはその実体を表現する名前にしましょう。
（ 書籍 Clean Code の第二章、「意味のある名前」を読んでみるといいですね）

2022-06-03 03:15 UTC, t-ita commented on src/main/java/com/recordofexpense/recordofexpense/controller/ExpenseController.java
> +        model.addAttribute("categoryLists", categoryList);
`categoryList` は「カテゴリーのリスト（一覧）」という意味かと思いますが、それを受け取る属性名を `categoryLists` としている意図がわかりません。
属性名から察するに、カテゴリーの一覧が複数あるイメージでしょうか？その名称と渡しているデータは一致していますか？

2022-06-06 06:25 UTC, Ryoma137 commented on src/main/java/com/recordofexpense/recordofexpense/controller/ExpenseController.java
> +        model.addAttribute("categoryLists", categoryList);
カテゴリーの一覧は複数ではないので、受け取る属性名`categoryList`に修正しました。

2022-06-06 06:25 UTC, Ryoma137 commented on src/main/resources/templates/expense.html
> +                        th:text="${categoryList}"></option>
@t-ita 変数名`categoryList`を`categoryItem`に変更しました。レビューお願いします。

2022-06-06 07:28 UTC, Burning-Chai reviewed
細かい指摘ですが、コメントしました。確認お願いします！
(細かい指摘なので、無理に修正してもらわなくても大丈夫です)

2022-06-06 07:28 UTC, Burning-Chai commented on src/main/java/com/recordofexpense/recordofexpense/service/AmountService.java
> +        Set<String> eliminateDuplications = new LinkedHashSet<String>(originalCategoryList);
var (lombok なら vol というのもあるが) を使うのか使わないのか、ある程度の統一感があったほうが良いですね。
意図的に var を使わないときもあるので、ケースバイケースではありますが。。。

2022-06-07 01:31 UTC, t-ita approved these changes
@Ryoma137  指摘箇所については問題無いです。参考までに、コメントを追加したので確認しておいてください。

2022-06-07 01:31 UTC, t-ita commented on src/main/resources/templates/expense.html
> +                <option th:each="categoryItem : ${categoryList}" th:value="${categoryItem}"
@Ryoma137 
categoryItem でよい感じだと思います。
ちなみに、私がこういう処理を書くときは、以下の様に書きます。
```
<option th:each="category : ${categories}" th:value="${categoryItem}"
```
こんな風に、リスト・配列は複数形で表現したりします。
ただ、こうすると `category` が文字列だとわかりにくい、とか、`categories` がリストとわかりにくいという意見もあったりするので、好みの問題です。いずれにしても、意図を読み違えられないような名付けをしましょう。

2022-06-08 06:12 UTC, merged